import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
// import "../styles/globals.css";

import {
  ClerkProvider,
} from "@clerk/nextjs";
import NavBar from "@/component/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ClerkProvider>
        <NavBar/>
        <html lang="en">
        

            <body className="bg-gray-100 min-h-screen">{children}</body>
            
        </html>
      </ClerkProvider>
    </>
  );
}
